### ISSUE TITLE
inquiry/bug: percentage representation on the matrix

### ISSUE THREAD

**Issue by igarny** [esnet/maddash#25] opened 2016-01-07 17:04 UTC
Hi Andy,

I am not sure if this is a bug or I am missing something, but I have been inquired about the meaning of percentage on the dashboard view of MADDASH.
I guess this is the same value as the "Average" one at the "Current Results" block for any particular measurement view.
What confuses me though is the value under "Statistics". There I can see the "Average" value in greater precision, and the corresponding value from above seems to be just a round from this.

I see also that the "Statistics" block shows the detailed result from the Nagios check.

Would you have some other interpretation of the percentage values?

Best regards,
Ivan

Current Status: WARNING
Result of last check: WARNING
Message For Current Status: Average Loss is 0.007% 
Events:
NameDescriptionStartEndCheck Down
No events currently scheduled.
Statistics
Count: 12
graphUrl: /serviceTest/graphWidget.cgi?url=http://prod-psma-gn-01-buc-ro.geant.net/esmond/perfsonar/archive/&source=psmp-gn-owd-01.bud.hu.geant.net&dest=psmp-gn-owd-02.fra.de.geant.net
Max: 0.0833333333333333
Standard_Deviation: 0.0240562612162344
Average: 0.00694444444444444
maUrl: http://prod-psma-gn-01-buc-ro.geant.net/esmond/perfsonar/archive/
Min: 0

**Comment by arlake228** [comment] 2016-01-07 17:59
The check alarms on the average percentage of loss seen for all the data points in a given timeframe (as specified by -r). For example, if the check asks for 2 minutes worth of data and it lost 40 of 100 packets sent in the first minute and 60 of 100 packets sent in the second minute then the average of .4 and .6 is .5 which would be reported in the Average statistics section and displayed as 50% in the message. As you noted, the message rounds to the nearest 3 decimal places so it is easier to read.

Closing since this is not a bug.

**Closed by arlake228** 2016-01-07 17:59 UTC

**Comment by arlake228** [comment] 2016-01-07 18:16
One amendment to my example, the average would be reported as 50.0. The percentage is expressed as a whole number in the statistics, you don't have to multiply by 100.

**Comment by igarny** [comment] 2016-01-08 09:14
Hi Andy,

Please look at my printout again (or at any measurement with loss) and more specifically at the lines with "Average".
I see 2 possibilities here:
Either the Nagios check output and respectively the Statistics block of MADDASH UI calculate it in percentage, which is not obvious from the output
or
the value in Results block (and the matrix view) of MADDASH is not multiplied by 100 to convert it to percentage. Therefore it shows only the ratio of lost packages to the whole number of sent packages.

**Comment by arlake228** [comment] 2016-01-08 14:51
Per my second comment yesterday, the value in the statistics section is the
actual percentage, not a decimal that needs to be multiplied by 100. I
verified this with your output, comparing to the graphs on the esnet
dashboard and looking at the raw data in the MA. The percentage reported in
the message is correct and the value in the statistics section is
consistent (even if not obvious the first time you look) so it doesn't look
like a bug.

**Comment by igarny** [comment] 2016-01-08 17:27
Great Andy,

since you state that the calculated values by the Nagios check are in percentages, could you also confirm that the warning and the critical values are being verified in their absolute values.
OR 
how should we define the limits in the MADDASH config?

Best regards,
Ivan

**Comment by arlake228** [comment] 2016-01-11 15:35
Hi,

The maddash config matches the nagios check. If you specify a threshold of .1 then that means .1%. The help screen on the nagios check for -c and -w both state that loss when specified as a percentage is given as a number between 0-100 (e.g .1 is .1%, 5 is 5%, etc). 

Hope that helps,
Andy



On January 8, 2016 at 12:28:14 PM, Ivan Garnizov (notifications@github.com) wrote:

Great Andy,

since you state that the calculated values by the Nagios check are in percentages, could you also confirm that the warning and the critical values are being verified in their absolute values.
OR
how should we define the limits in the MADDASH config?

Best regards,
Ivan
